### ISSUE TITLE
README needs to be more helpful for non-Vega devs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegacapsule#29]
The README as it is relies on a lot of setup that people not working on [vegaprotocol/vega](https://github.com/vegaprotocol/vega) will not have. In particular:

1. The docker login auths with a different server to the docker pull, so step 3 fails if you haven't logged in to [ghcr.io](http://ghcr.io/) separately (README fix)
2. Step 2 could be nice and link to the Github token page and remind you to give it scope to read packages.
3. Start step 2 will fail if you haven't followed the starter guide and run https://github.com/vegaprotocol/vega/blob/develop/GETTING_STARTED.md#github-authentication-and-git-configurations and set set GONOSUMDB [code.vegaprotocol.io/*](http://code.vegaprotocol.io/*)
4. Start step 4 will fail if you haven't already built and made `vega` && `data-node` && `vega-wallet` available on your path

# Tasks
- [x] Update `docker login` command to use ghcr.io
- [x] Update 'github token' to link to https://github.com/settings/tokens/new, and remind the user to give it `read` permissions for images
- [x] Include the git configuration / `GONOSUMDB` environment variable so that `go install` will not fail
- [x] Add an instruction stating that the three projects need to be built and available locally (until #28)

# Related
- [ ] https://github.com/vegaprotocol/data-node/issues/396
