### ISSUE TITLE
New nodes are not respected in the config templating

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#368]
Let's say We have the following line of the config in the `data-node` config:

```toml
BootstrapPeers = [{{- range $i, $peer := .IPSFPeers -}}
      {{- if ne $i 0 }},{{end -}}
      "/ip4/127.0.0.1/tcp/4{{ printf "%02d" $peer.Index }}5/ipfs/{{ $peer.ID }}"
    {{- end -}}]
```

Then when we have one data node in the `config.hcl` We get the following output:

```toml
BootstrapPeers = ["/ip4/127.0.0.1/tcp/4025/ipfs/12D3KooWDhDcgBCEYxqAsQGYkNWQboeVacCMEuhMtRJbYsiKPFLH"]
```

Then, We want to add a node with the following command:

```bash
vegacapsule nodes add --base-on "$DATA_NODE_BASE" --start=false --out-path ./new-data-node.json;
```

And We are getting the same config as previously, but I believe we should get two bootstrap nodes:

```toml
BootstrapPeers = ["/ip4/127.0.0.1/tcp/4025/ipfs/.....", "/ip4/127.0.0.1/tcp/4035/ipfs/....."]
```

I am currently doing this fix manually as the workaround.

# TODO:

1. [ ] Rethink if this solution needs to be implemented
2. [ ] Implement the solution
3. [ ] Make sure no pipeline is broken.
